### ISSUE TITLE
URL zum Embedded Web GIS Client lautet offenbar neu anders

### ISSUE THREAD

**Issue by schmandr** [sogis/pipelines#2]
Die URL zum Embedded Web GIS Client muss neu offenbar `api/embed/v1` lauten.

https://github.com/sogis/pipelines/blob/f0af1f6581b96aa074fbdf0ad9dbb69aa6786a4d/api_webgisclient/api-gateway/resources.yaml#L242

**Comment by pfeimich** [comment]
Changed URL due to AGI guidelines
Fixed in 2513a410c42ec2344cbae407082278b826b3e927
